baseurl: "https://icossa.com/hawaii-wedding/"
languageCode: "ja"
title: "ハワいこ！〜二人きりのハワイウェディングの軌跡〜"
permalinks:
  post: "/:slug/"

Params:
  Author: "icossahawaii"
  Birth: "Sun, March 3, 1988"
  DateForm: "Mon, Jan 2, 2006"
  GoogleAnalyticsUserID: "UA-74088325-2"
  Twitter: "icossahawaii"
  Github: ""
  ShowTagCloud: True
  ShowRelatedPost: True
  Disqus: "meganii"
  SyntaxHighlightTheme: "solarized_dark.min.css"
  logo: "/images/meganii_logo.png"

MetadataFormat: "yaml"

taxonomies:
  tag: "tags"
  category: "category"

author:
    name: "icossahawaii"
    homepage: "https://icossa.com/hawaii-wedding/"

Copyright:
