baseurl: "https://icossa.com/kabu/"
languageCode: "ja"
title: "のんびり投資でいこっさ！"
permalinks:
  post: "/:year/:month/:day/:slug/"

Params:
  Author: "meganii"
  Birth: "Sun, March 3, 1988"
  DateForm: "Mon, Jan 2, 2006"
  GoogleAnalyticsUserID: "UA-74088325-1"
  Twitter: "https://twitter.com/"
  ShowTagCloud: True
  ShowRelatedPost: True
  Disqus: "meganii"
  SyntaxHighlightTheme: "solarized_dark.min.css"
  logo: "/kabu/images/meganii_logo.png"

MetadataFormat: "yaml"

taxonomies:
  tag: "tags"
  category: "category"

author:
    name: "meganii"
    homepage: "https://meganii.com/"

Copyright:
